loggin:
  config: classpath:log4j2.xml
  
spring:
  datasource:
    url: jdbc:mysql://192.168.0.102:3306/oauth?useUnicode=true&characterEncoding=UTF-8
    username: killbuff
    password: KillBuff.com1991
    driverClassName: com.mysql.jdbc.Driver