loggin:
  config: classpath:log4j2.xml
  
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/oauth?useUnicode=true&characterEncoding=UTF-8&useSSL=false&autoReconnect=true
    username: root
    password: 
    driverClassName: com.mysql.jdbc.Driver